INSERT INTO COUNTY_ENTITY VALUES(1,'Verkiu');
INSERT INTO COUNTY_ENTITY VALUES(2,'Zirmunu');
INSERT INTO COUNTY_ENTITY VALUES(3,'Antakalnio');
INSERT INTO COUNTY_ENTITY VALUES(4,'Test');
INSERT INTO COUNTY_ENTITY VALUES(5,'bcvbcvbcv');
INSERT INTO COUNTY_ENTITY VALUES(6,'sdfsdfsd');
