

-- MySQL Script generated by MySQL Workbench
-- 01/23/17 11:18:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apygarda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Apygarda` (
  `Apygardos_ID` INT NOT NULL,
  `Pavadinimas` VARCHAR(45) NULL,
  PRIMARY KEY (`Apygardos_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vienmandatės_balsų_registravimas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vienmandatės_balsų_registravimas` (
  `Apylinkės_ID` INT NOT NULL,
  `Registracijos_laikas` DATETIME NULL,
  `Sugadinti_biuleteniai` INT NULL,
  PRIMARY KEY (`Apylinkės_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apylinkė`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Apylinkė` (
  `Apylinkės_ID` INT NOT NULL,
  `Pavadinimas` VARCHAR(45) NULL,
  `Adresas` VARCHAR(45) NULL,
  `Rinkėjų skaičius` INT NULL,
  `Apygardos_ID` INT NOT NULL,
  PRIMARY KEY (`Apylinkės_ID`),
  INDEX `fk_Apylinkė_Apygarda1_idx` (`Apygardos_ID` ASC),
  INDEX `fk_Apylinkė_Vienmandatės_balsų_registravimas1_idx` (`Apylinkės_ID` ASC),
  CONSTRAINT `fk_Apylinkė_Apygarda1`
    FOREIGN KEY (`Apygardos_ID`)
    REFERENCES `mydb`.`Apygarda` (`Apygardos_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apylinkė_Vienmandatės_balsų_registravimas1`
    FOREIGN KEY (`Apylinkės_ID`)
    REFERENCES `mydb`.`Vienmandatės_balsų_registravimas` (`Apylinkės_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apylinkės atstovas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Apylinkės atstovas` (
  `Atstovo_ID` INT NOT NULL,
  `Vardas` VARCHAR(45) NULL,
  `Pavardė` VARCHAR(45) NULL,
  `Vartotojo_vardas` VARCHAR(45) NULL,
  `Slaptažodis` VARCHAR(45) NULL,
  `Apylinkės_ID` INT NOT NULL,
  PRIMARY KEY (`Atstovo_ID`),
  INDEX `fk_Apylinkės atstovas_Apylinkė1_idx` (`Apylinkės_ID` ASC),
  CONSTRAINT `fk_Apylinkės atstovas_Apylinkė1`
    FOREIGN KEY (`Apylinkės_ID`)
    REFERENCES `mydb`.`Apylinkė` (`Apylinkės_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Partija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Partija` (
  `Partijos_ID` INT NOT NULL,
  `Pavadinimas` VARCHAR(45) NULL,
  PRIMARY KEY (`Partijos_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kandidatas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kandidatas` (
  `Kandidato_AK` INT NOT NULL,
  `Vardas` VARCHAR(45) NULL,
  `Pavardė` VARCHAR(45) NULL,
  `Gimimo_data` DATE NULL,
  `Aprašymas` VARCHAR(45) NULL,
  `Apygardos_ID` INT NULL,
  `Partijos_ID` INT NOT NULL,
  PRIMARY KEY (`Kandidato_AK`, `Partijos_ID`),
  INDEX `fk_Kandidatas_Partija1_idx` (`Partijos_ID` ASC),
  CONSTRAINT `fk_Kandidatas_Partija1`
    FOREIGN KEY (`Partijos_ID`)
    REFERENCES `mydb`.`Partija` (`Partijos_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vienmandatės_balsai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vienmandatės_balsai` (
  `Balsų_skaičius` VARCHAR(45) NULL,
  `Apylinkės_ID` INT NOT NULL,
  `Kandidato_AK` INT NOT NULL,
  PRIMARY KEY (`Apylinkės_ID`, `Kandidato_AK`),
  INDEX `fk_Vienmandatės_balsai_Vienmandatės_balsų_registravimas1_idx` (`Apylinkės_ID` ASC),
  CONSTRAINT `fk_Vienmandatės_balsai_Kandidatas1`
    FOREIGN KEY (`Kandidato_AK`)
    REFERENCES `mydb`.`Kandidatas` (`Kandidato_AK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vienmandatės_balsai_Vienmandatės_balsų_registravimas1`
    FOREIGN KEY (`Apylinkės_ID`)
    REFERENCES `mydb`.`Vienmandatės_balsų_registravimas` (`Apylinkės_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Daugiamandatės_balsų_registracija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Daugiamandatės_balsų_registracija` (
  `Apylinkės_ID` INT NOT NULL,
  `Laikas` DATETIME NULL,
  `Sugadinti_biuleteniai` INT NULL,
  PRIMARY KEY (`Apylinkės_ID`),
  INDEX `fk_Daugiamandatės_balsų_registracija_Apylinkė1_idx` (`Apylinkės_ID` ASC),
  CONSTRAINT `fk_Daugiamandatės_balsų_registracija_Apylinkė1`
    FOREIGN KEY (`Apylinkės_ID`)
    REFERENCES `mydb`.`Apylinkė` (`Apylinkės_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Daugiamandatės_balsai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Daugiamandatės_balsai` (
  `Partijos_ID` INT NOT NULL,
  `Apylinkės_ID` INT NOT NULL,
  `Balsų_skaičius` INT NULL,
  PRIMARY KEY (`Partijos_ID`, `Apylinkės_ID`),
  INDEX `fk_Daugiamandatės_balsai_Partija1_idx` (`Partijos_ID` ASC),
  INDEX `fk_Daugiamandatės_balsai_Daugiamandatės_balsų_registraci_idx` (`Apylinkės_ID` ASC),
  CONSTRAINT `fk_Daugiamandatės_balsai_Partija1`
    FOREIGN KEY (`Partijos_ID`)
    REFERENCES `mydb`.`Partija` (`Partijos_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Daugiamandatės_balsai_Daugiamandatės_balsų_registracija1`
    FOREIGN KEY (`Apylinkės_ID`)
    REFERENCES `mydb`.`Daugiamandatės_balsų_registracija` (`Apylinkės_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;